"""initial schema

Revision ID: 798469680354
Revises: 
Create Date: 2026-09-12 02:25:04.261989+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# Custom portable column types (exact Decimal on SQLite, native types on PostgreSQL).
import asm.db.types


revision = '798469680354'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('detail', asm.db.types.JSONDict(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('before', asm.db.types.JSONDict(), nullable=False),
    sa.Column('after', asm.db.types.JSONDict(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('backtests',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', asm.db.types.JSONDict(), nullable=False),
    sa.Column('results', asm.db.types.JSONDict(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    op.create_index(op.f('ix_backtests_status'), 'backtests', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('decision_id', asm.db.types.GUID(), nullable=True),
    sa.Column('position_id', asm.db.types.GUID(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('trader_wallet', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('input_mint', sa.String(length=64), nullable=False),
    sa.Column('output_mint', sa.String(length=64), nullable=False),
    sa.Column('in_amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('size_usd', asm.db.types.Money(), nullable=False),
    sa.Column('slippage_bps', sa.Integer(), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('reservation_id', sa.String(length=64), nullable=True),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_decision_id'), 'orders', ['decision_id'], unique=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_mode'), 'orders', ['mode'], unique=False)
    op.create_index(op.f('ix_orders_position_id'), 'orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_token_mint'), 'orders', ['token_mint'], unique=False)
    op.create_index(op.f('ix_orders_trader_wallet'), 'orders', ['trader_wallet'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('active_capital_usd', asm.db.types.Money(), nullable=False),
    sa.Column('cash_usd', asm.db.types.Money(), nullable=False),
    sa.Column('deployed_usd', asm.db.types.Money(), nullable=False),
    sa.Column('unrealized_pnl_usd', asm.db.types.Money(), nullable=False),
    sa.Column('realized_pnl_today_usd', asm.db.types.Money(), nullable=False),
    sa.Column('total_equity_usd', asm.db.types.Money(), nullable=False),
    sa.Column('high_water_mark_usd', asm.db.types.Money(), nullable=False),
    sa.Column('drawdown_pct', asm.db.types.Money(), nullable=False),
    sa.Column('harvested_total_usd', asm.db.types.Money(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('sol_balance', asm.db.types.Money(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index(op.f('ix_portfolio_snapshots_captured_at'), 'portfolio_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_mode'), 'portfolio_snapshots', ['mode'], unique=False)
    op.create_table('positions',
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('trader_wallet', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('cost_basis_usd', asm.db.types.Money(), nullable=False),
    sa.Column('realized_pnl_usd', asm.db.types.Money(), nullable=False),
    sa.Column('fees_usd', asm.db.types.Money(), nullable=False),
    sa.Column('entry_price', asm.db.types.Money(), nullable=False),
    sa.Column('current_price', asm.db.types.Money(), nullable=False),
    sa.Column('peak_price', asm.db.types.Money(), nullable=False),
    sa.Column('trailing_armed', sa.Boolean(), nullable=False),
    sa.Column('tp_levels_hit', asm.db.types.IntList(), nullable=False),
    sa.Column('source_trade_id', asm.db.types.GUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_mode'), 'positions', ['mode'], unique=False)
    op.create_index('ix_positions_open', 'positions', ['mode', 'status', 'token_mint'], unique=False)
    op.create_index(op.f('ix_positions_opened_at'), 'positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_token_mint'), 'positions', ['token_mint'], unique=False)
    op.create_index(op.f('ix_positions_trader_wallet'), 'positions', ['trader_wallet'], unique=False)
    op.create_table('profit_harvest_events',
    sa.Column('rule_id', asm.db.types.GUID(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('equity_before_usd', asm.db.types.Money(), nullable=False),
    sa.Column('equity_after_usd', asm.db.types.Money(), nullable=False),
    sa.Column('profit_since_hwm_usd', asm.db.types.Money(), nullable=False),
    sa.Column('harvested_usd', asm.db.types.Money(), nullable=False),
    sa.Column('retained_usd', asm.db.types.Money(), nullable=False),
    sa.Column('new_high_water_mark_usd', asm.db.types.Money(), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('detail', asm.db.types.JSONDict(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profit_harvest_events'))
    )
    op.create_index(op.f('ix_profit_harvest_events_mode'), 'profit_harvest_events', ['mode'], unique=False)
    op.create_index(op.f('ix_profit_harvest_events_occurred_at'), 'profit_harvest_events', ['occurred_at'], unique=False)
    op.create_table('profit_harvest_rules',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold_pct', asm.db.types.Money(), nullable=False),
    sa.Column('take_pct', asm.db.types.Money(), nullable=False),
    sa.Column('min_active_capital_usd', asm.db.types.Money(), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('config', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profit_harvest_rules')),
    sa.UniqueConstraint('name', name=op.f('uq_profit_harvest_rules_name'))
    )
    op.create_table('risk_events',
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', asm.db.types.JSONDict(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_kind'), 'risk_events', ['kind'], unique=False)
    op.create_index(op.f('ix_risk_events_occurred_at'), 'risk_events', ['occurred_at'], unique=False)
    op.create_table('source_trades',
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('slot', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('quote_mint', sa.String(length=64), nullable=False),
    sa.Column('token_amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('quote_amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('source_price', asm.db.types.Money(), nullable=False),
    sa.Column('source_value_usd', asm.db.types.Money(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('source_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_trades'))
    )
    op.create_index(op.f('ix_source_trades_dedupe_key'), 'source_trades', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_source_trades_signature'), 'source_trades', ['signature'], unique=False)
    op.create_index(op.f('ix_source_trades_source_confirmed_at'), 'source_trades', ['source_confirmed_at'], unique=False)
    op.create_index(op.f('ix_source_trades_token_mint'), 'source_trades', ['token_mint'], unique=False)
    op.create_index(op.f('ix_source_trades_wallet'), 'source_trades', ['wallet'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', asm.db.types.JSONDict(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_configs')),
    sa.UniqueConstraint('name', 'version', name='uq_strategy_version')
    )
    op.create_index(op.f('ix_strategy_configs_active'), 'strategy_configs', ['active'], unique=False)
    op.create_index(op.f('ix_strategy_configs_name'), 'strategy_configs', ['name'], unique=False)
    op.create_table('system_events',
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=True),
    sa.Column('payload', asm.db.types.JSONDict(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_aggregate_id'), 'system_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_occurred_at'), 'system_events', ['occurred_at'], unique=False)
    op.create_table('token_risk_scores',
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('mint_authority_active', sa.Boolean(), nullable=True),
    sa.Column('freeze_authority_active', sa.Boolean(), nullable=True),
    sa.Column('lp_burned', sa.Boolean(), nullable=True),
    sa.Column('top10_holder_pct', asm.db.types.Money(), nullable=True),
    sa.Column('is_honeypot', sa.Boolean(), nullable=True),
    sa.Column('reasons', asm.db.types.StringList(), nullable=False),
    sa.Column('detail', asm.db.types.JSONDict(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_risk_scores'))
    )
    op.create_index(op.f('ix_token_risk_scores_evaluated_at'), 'token_risk_scores', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_token_risk_scores_mint'), 'token_risk_scores', ['mint'], unique=False)
    op.create_table('token_snapshots',
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('price_usd', asm.db.types.Money(), nullable=False),
    sa.Column('liquidity_usd', asm.db.types.Money(), nullable=False),
    sa.Column('market_cap_usd', asm.db.types.Money(), nullable=False),
    sa.Column('volume_24h_usd', asm.db.types.Money(), nullable=False),
    sa.Column('holder_count', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_snapshots'))
    )
    op.create_index(op.f('ix_token_snapshots_captured_at'), 'token_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_token_snapshots_mint'), 'token_snapshots', ['mint'], unique=False)
    op.create_table('tokens',
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('created_at_chain', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployer', sa.String(length=64), nullable=True),
    sa.Column('meta', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens'))
    )
    op.create_index(op.f('ix_tokens_deployer'), 'tokens', ['deployer'], unique=False)
    op.create_index(op.f('ix_tokens_mint'), 'tokens', ['mint'], unique=True)
    op.create_table('trade_decisions',
    sa.Column('candidate_id', asm.db.types.GUID(), nullable=False),
    sa.Column('source_trade_id', asm.db.types.GUID(), nullable=True),
    sa.Column('trader_wallet', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_codes', asm.db.types.StringList(), nullable=False),
    sa.Column('gates', asm.db.types.JSONDict(), nullable=False),
    sa.Column('inputs', asm.db.types.JSONDict(), nullable=False),
    sa.Column('size_usd', asm.db.types.Money(), nullable=False),
    sa.Column('size_pct', asm.db.types.Money(), nullable=False),
    sa.Column('size_multiplier', asm.db.types.Money(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('observation_latency_ms', sa.Integer(), nullable=True),
    sa.Column('analysis_latency_ms', sa.Integer(), nullable=True),
    sa.Column('execution_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_copy_latency_ms', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_decisions'))
    )
    op.create_index('ix_decisions_mode_time', 'trade_decisions', ['mode', 'decided_at'], unique=False)
    op.create_index(op.f('ix_trade_decisions_candidate_id'), 'trade_decisions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_trade_decisions_decided_at'), 'trade_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_trade_decisions_decision'), 'trade_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_trade_decisions_mode'), 'trade_decisions', ['mode'], unique=False)
    op.create_index(op.f('ix_trade_decisions_source_trade_id'), 'trade_decisions', ['source_trade_id'], unique=False)
    op.create_index(op.f('ix_trade_decisions_token_mint'), 'trade_decisions', ['token_mint'], unique=False)
    op.create_index(op.f('ix_trade_decisions_trader_wallet'), 'trade_decisions', ['trader_wallet'], unique=False)
    op.create_table('trader_relationships',
    sa.Column('wallet_a', sa.String(length=64), nullable=False),
    sa.Column('wallet_b', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('strength', asm.db.types.Money(), nullable=False),
    sa.Column('evidence', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trader_relationships')),
    sa.UniqueConstraint('wallet_a', 'wallet_b', 'relation', name='uq_rel')
    )
    op.create_index(op.f('ix_trader_relationships_wallet_a'), 'trader_relationships', ['wallet_a'], unique=False)
    op.create_index(op.f('ix_trader_relationships_wallet_b'), 'trader_relationships', ['wallet_b'], unique=False)
    op.create_table('traders',
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('composite_score', asm.db.types.Money(), nullable=False),
    sa.Column('confidence', asm.db.types.Money(), nullable=False),
    sa.Column('copyability_score', asm.db.types.Money(), nullable=False),
    sa.Column('live_replication_score', asm.db.types.Money(), nullable=True),
    sa.Column('risk_budget_pct', asm.db.types.Money(), nullable=False),
    sa.Column('size_multiplier', asm.db.types.Money(), nullable=False),
    sa.Column('median_hold_seconds', sa.Integer(), nullable=True),
    sa.Column('latency_tolerance_ms', sa.Integer(), nullable=True),
    sa.Column('avg_trade_size_usd', asm.db.types.Money(), nullable=True),
    sa.Column('win_rate', asm.db.types.Money(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('degraded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traders')),
    sa.UniqueConstraint('chain', 'wallet_address', name='uq_traders_chain_wallet')
    )
    op.create_index(op.f('ix_traders_last_trade_at'), 'traders', ['last_trade_at'], unique=False)
    op.create_index(op.f('ix_traders_status'), 'traders', ['status'], unique=False)
    op.create_index('ix_traders_status_score', 'traders', ['status', 'composite_score'], unique=False)
    op.create_index(op.f('ix_traders_wallet_address'), 'traders', ['wallet_address'], unique=False)
    op.create_table('treasury_transfers',
    sa.Column('harvest_event_id', asm.db.types.GUID(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('amount_usd', asm.db.types.Money(), nullable=False),
    sa.Column('amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treasury_transfers'))
    )
    op.create_index(op.f('ix_treasury_transfers_occurred_at'), 'treasury_transfers', ['occurred_at'], unique=False)
    op.create_table('executions',
    sa.Column('order_id', asm.db.types.GUID(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('expected_price', asm.db.types.Money(), nullable=False),
    sa.Column('actual_price', asm.db.types.Money(), nullable=False),
    sa.Column('source_price', asm.db.types.Money(), nullable=False),
    sa.Column('expected_slippage_pct', asm.db.types.Money(), nullable=False),
    sa.Column('actual_slippage_pct', asm.db.types.Money(), nullable=False),
    sa.Column('in_amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('out_amount_raw', asm.db.types.RawAmount(), nullable=False),
    sa.Column('value_usd', asm.db.types.Money(), nullable=False),
    sa.Column('network_fee_lamports', sa.BigInteger(), nullable=False),
    sa.Column('priority_fee_lamports', sa.BigInteger(), nullable=False),
    sa.Column('route', sa.String(length=256), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('source_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_executions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_mode'), 'executions', ['mode'], unique=False)
    op.create_index(op.f('ix_executions_order_id'), 'executions', ['order_id'], unique=False)
    op.create_index(op.f('ix_executions_signature'), 'executions', ['signature'], unique=False)
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_table('position_events',
    sa.Column('position_id', asm.db.types.GUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('execution_id', asm.db.types.GUID(), nullable=True),
    sa.Column('amount_raw_delta', asm.db.types.RawAmount(), nullable=False),
    sa.Column('usd_delta', asm.db.types.Money(), nullable=False),
    sa.Column('price', asm.db.types.Money(), nullable=False),
    sa.Column('realized_pnl_usd', asm.db.types.Money(), nullable=False),
    sa.Column('fees_usd', asm.db.types.Money(), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('detail', asm.db.types.JSONDict(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_events_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_events')),
    sa.UniqueConstraint('position_id', 'seq', name='uq_position_event_seq')
    )
    op.create_index(op.f('ix_position_events_event_type'), 'position_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_position_events_occurred_at'), 'position_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_position_events_position_id'), 'position_events', ['position_id'], unique=False)
    op.create_table('trade_candidates',
    sa.Column('source_trade_id', asm.db.types.GUID(), nullable=False),
    sa.Column('trader_wallet', sa.String(length=64), nullable=False),
    sa.Column('token_mint', sa.String(length=64), nullable=False),
    sa.Column('market_snapshot', asm.db.types.JSONDict(), nullable=False),
    sa.Column('quote_snapshot', asm.db.types.JSONDict(), nullable=False),
    sa.Column('confirmations', asm.db.types.StringList(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_trade_id'], ['source_trades.id'], name=op.f('fk_trade_candidates_source_trade_id_source_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_candidates'))
    )
    op.create_index(op.f('ix_trade_candidates_created_at'), 'trade_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_candidates_source_trade_id'), 'trade_candidates', ['source_trade_id'], unique=False)
    op.create_index(op.f('ix_trade_candidates_token_mint'), 'trade_candidates', ['token_mint'], unique=False)
    op.create_index(op.f('ix_trade_candidates_trader_wallet'), 'trade_candidates', ['trader_wallet'], unique=False)
    op.create_table('trader_daily_metrics',
    sa.Column('trader_id', asm.db.types.GUID(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('source_pnl_usd', asm.db.types.Money(), nullable=False),
    sa.Column('copied_pnl_usd', asm.db.types.Money(), nullable=False),
    sa.Column('copyable_pnl_usd', asm.db.types.Money(), nullable=False),
    sa.Column('max_drawdown_pct', asm.db.types.Money(), nullable=False),
    sa.Column('meta', asm.db.types.JSONDict(), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], name=op.f('fk_trader_daily_metrics_trader_id_traders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trader_daily_metrics')),
    sa.UniqueConstraint('trader_id', 'day', name='uq_trader_daily')
    )
    op.create_index(op.f('ix_trader_daily_metrics_day'), 'trader_daily_metrics', ['day'], unique=False)
    op.create_index(op.f('ix_trader_daily_metrics_trader_id'), 'trader_daily_metrics', ['trader_id'], unique=False)
    op.create_table('trader_scores',
    sa.Column('trader_id', asm.db.types.GUID(), nullable=False),
    sa.Column('performance', asm.db.types.Money(), nullable=False),
    sa.Column('consistency', asm.db.types.Money(), nullable=False),
    sa.Column('longevity', asm.db.types.Money(), nullable=False),
    sa.Column('risk_adjusted', asm.db.types.Money(), nullable=False),
    sa.Column('copyability', asm.db.types.Money(), nullable=False),
    sa.Column('live_replication', asm.db.types.Money(), nullable=True),
    sa.Column('composite', asm.db.types.Money(), nullable=False),
    sa.Column('confidence', asm.db.types.Money(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('inputs', asm.db.types.JSONDict(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', asm.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.id'], name=op.f('fk_trader_scores_trader_id_traders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trader_scores'))
    )
    op.create_index(op.f('ix_trader_scores_computed_at'), 'trader_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_trader_scores_trader_id'), 'trader_scores', ['trader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trader_scores_trader_id'), table_name='trader_scores')
    op.drop_index(op.f('ix_trader_scores_computed_at'), table_name='trader_scores')
    op.drop_table('trader_scores')
    op.drop_index(op.f('ix_trader_daily_metrics_trader_id'), table_name='trader_daily_metrics')
    op.drop_index(op.f('ix_trader_daily_metrics_day'), table_name='trader_daily_metrics')
    op.drop_table('trader_daily_metrics')
    op.drop_index(op.f('ix_trade_candidates_trader_wallet'), table_name='trade_candidates')
    op.drop_index(op.f('ix_trade_candidates_token_mint'), table_name='trade_candidates')
    op.drop_index(op.f('ix_trade_candidates_source_trade_id'), table_name='trade_candidates')
    op.drop_index(op.f('ix_trade_candidates_created_at'), table_name='trade_candidates')
    op.drop_table('trade_candidates')
    op.drop_index(op.f('ix_position_events_position_id'), table_name='position_events')
    op.drop_index(op.f('ix_position_events_occurred_at'), table_name='position_events')
    op.drop_index(op.f('ix_position_events_event_type'), table_name='position_events')
    op.drop_table('position_events')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_index(op.f('ix_executions_signature'), table_name='executions')
    op.drop_index(op.f('ix_executions_order_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_mode'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_treasury_transfers_occurred_at'), table_name='treasury_transfers')
    op.drop_table('treasury_transfers')
    op.drop_index(op.f('ix_traders_wallet_address'), table_name='traders')
    op.drop_index('ix_traders_status_score', table_name='traders')
    op.drop_index(op.f('ix_traders_status'), table_name='traders')
    op.drop_index(op.f('ix_traders_last_trade_at'), table_name='traders')
    op.drop_table('traders')
    op.drop_index(op.f('ix_trader_relationships_wallet_b'), table_name='trader_relationships')
    op.drop_index(op.f('ix_trader_relationships_wallet_a'), table_name='trader_relationships')
    op.drop_table('trader_relationships')
    op.drop_index(op.f('ix_trade_decisions_trader_wallet'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_token_mint'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_source_trade_id'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_mode'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_decision'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_decided_at'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_candidate_id'), table_name='trade_decisions')
    op.drop_index('ix_decisions_mode_time', table_name='trade_decisions')
    op.drop_table('trade_decisions')
    op.drop_index(op.f('ix_tokens_mint'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_deployer'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_token_snapshots_mint'), table_name='token_snapshots')
    op.drop_index(op.f('ix_token_snapshots_captured_at'), table_name='token_snapshots')
    op.drop_table('token_snapshots')
    op.drop_index(op.f('ix_token_risk_scores_mint'), table_name='token_risk_scores')
    op.drop_index(op.f('ix_token_risk_scores_evaluated_at'), table_name='token_risk_scores')
    op.drop_table('token_risk_scores')
    op.drop_index(op.f('ix_system_events_occurred_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_aggregate_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_strategy_configs_name'), table_name='strategy_configs')
    op.drop_index(op.f('ix_strategy_configs_active'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_source_trades_wallet'), table_name='source_trades')
    op.drop_index(op.f('ix_source_trades_token_mint'), table_name='source_trades')
    op.drop_index(op.f('ix_source_trades_source_confirmed_at'), table_name='source_trades')
    op.drop_index(op.f('ix_source_trades_signature'), table_name='source_trades')
    op.drop_index(op.f('ix_source_trades_dedupe_key'), table_name='source_trades')
    op.drop_table('source_trades')
    op.drop_index(op.f('ix_risk_events_occurred_at'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_kind'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('profit_harvest_rules')
    op.drop_index(op.f('ix_profit_harvest_events_occurred_at'), table_name='profit_harvest_events')
    op.drop_index(op.f('ix_profit_harvest_events_mode'), table_name='profit_harvest_events')
    op.drop_table('profit_harvest_events')
    op.drop_index(op.f('ix_positions_trader_wallet'), table_name='positions')
    op.drop_index(op.f('ix_positions_token_mint'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_opened_at'), table_name='positions')
    op.drop_index('ix_positions_open', table_name='positions')
    op.drop_index(op.f('ix_positions_mode'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_mode'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_captured_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_orders_trader_wallet'), table_name='orders')
    op.drop_index(op.f('ix_orders_token_mint'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_position_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_mode'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_decision_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_backtests_status'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
